export const cuisineList = [
    "American",
    "BBQ",
    "Burgers",
    "Cafe",
    "Argentine",
    "Peruvian",
    "South African",
    "Japanese",
    "Greek",
    "Belgian",
    "Indonesian",
    "Moroccan",
    "Thai",
    "Filipino",
    "French",
    "Singaporean",
    "Italian",
    "Caribbean",
    "Portuguese",
    "Vietnamese",
    "Indian",
    "Mexican",
    "Korean",
    "Chinese",
    "Russian",
    "German",
    "Brazilian",
    "Lebanese",
    "Middle Eastern",
]